### ISSUE TITLE
Exception on loading BITONALTILE

### ISSUE THREAD

**Issue by DTeuchert** [twenzel/CGM#6]
On loading a binary WebCGM which contains a `BITONALTILE` in a `BEGTILEARRAY` the library throws an exception `Error on EnsureAllArgumentsWereRead in BitonalTile command for file 'xx'!` 

The total size of the file is 9.144 Bytes, so I assume that the file size is not the issue.

The Stacktrace is listed below:
`   at codessentials.CGM.Commands.Command.Assert(Boolean isCorrect, String errorMessage) in C:\Users\teuchert_d\source\github\CGM\src\Commands\Command.cs:line 282
   at codessentials.CGM.Import.DefaultBinaryReader.EnsureAllArgumentsWereRead() in C:\Users\teuchert_d\source\github\CGM\src\Import\DefaultBinaryReader.cs:line 227
   at codessentials.CGM.Import.DefaultBinaryReader.ReadCommand() in C:\Users\teuchert_d\source\github\CGM\src\Import\DefaultBinaryReader.cs:line 343
   at codessentials.CGM.Import.DefaultBinaryReader.ReadCommands() in C:\Users\teuchert_d\source\github\CGM\src\Import\DefaultBinaryReader.cs:line 64
   at codessentials.CGM.BinaryCgmFile.ReadData(Stream stream) in C:\Users\teuchert_d\source\github\CGM\src\BinaryCGMFile.cs:line 98
   at codessentials.CGM.BinaryCgmFile.ReadData(String fileName) in C:\Users\teuchert_d\source\github\CGM\src\BinaryCGMFile.cs:line 106
   at codessentials.CGM.BinaryCgmFile..ctor(String fileName) in C:\Users\teuchert_d\source\github\CGM\src\BinaryCGMFile.cs:line 32
   at CgmReader.Services.CgmReader.ConvertBinaryToTextCgmFile(String filePath, Boolean storeFile) in C:\Users\teuchert_d\source\CgmReader\CgmReader.Core\Services\CgmReader.cs:line 21
   at CgmReader.Program.Main(String[] args) in C:\Users\teuchert_d\source\CgmReader\CgmReader\Program.cs:line 44`

**Comment by twenzel** [comment]
Thank you for reporting this.
I'll have a look into this.

**Comment by DTeuchert** [comment]
@twenzel do you have any findings regarding the issue?

**Comment by twenzel** [comment]
@DTeuchert Sorry, I didn't found the time yet.

**Comment by DTeuchert** [comment]
@twenzel, do you find any time to look into the issue? The issue is still relevant.

**Comment by twenzel** [comment]
Closed by #7

**Comment by twenzel** [comment]
@DTeuchert New NuGet package 1.1.5 is available
